# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anthony/projects/cvec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anthony/projects/cvec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthony/projects/cvec/CMakeFiles /Users/anthony/projects/cvec//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthony/projects/cvec/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ctools

# Build rule for target.
ctools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctools
.PHONY : ctools

# fast build rule for target.
ctools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/build
.PHONY : ctools/fast

#=============================================================================
# Target rules for targets named vecExample

# Build rule for target.
vecExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vecExample
.PHONY : vecExample

# fast build rule for target.
vecExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vecExample.dir/build.make CMakeFiles/vecExample.dir/build
.PHONY : vecExample/fast

#=============================================================================
# Target rules for targets named listExample

# Build rule for target.
listExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 listExample
.PHONY : listExample

# fast build rule for target.
listExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/listExample.dir/build.make CMakeFiles/listExample.dir/build
.PHONY : listExample/fast

#=============================================================================
# Target rules for targets named mapExample

# Build rule for target.
mapExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mapExample
.PHONY : mapExample

# fast build rule for target.
mapExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapExample.dir/build.make CMakeFiles/mapExample.dir/build
.PHONY : mapExample/fast

#=============================================================================
# Target rules for targets named queueExample

# Build rule for target.
queueExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 queueExample
.PHONY : queueExample

# fast build rule for target.
queueExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queueExample.dir/build.make CMakeFiles/queueExample.dir/build
.PHONY : queueExample/fast

#=============================================================================
# Target rules for targets named stackExample

# Build rule for target.
stackExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stackExample
.PHONY : stackExample

# fast build rule for target.
stackExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stackExample.dir/build.make CMakeFiles/stackExample.dir/build
.PHONY : stackExample/fast

#=============================================================================
# Target rules for targets named ctoolsTests

# Build rule for target.
ctoolsTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctoolsTests
.PHONY : ctoolsTests

# fast build rule for target.
ctoolsTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/build
.PHONY : ctoolsTests/fast

examples/list.o: examples/list.c.o
.PHONY : examples/list.o

# target to build an object file
examples/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/listExample.dir/build.make CMakeFiles/listExample.dir/examples/list.c.o
.PHONY : examples/list.c.o

examples/list.i: examples/list.c.i
.PHONY : examples/list.i

# target to preprocess a source file
examples/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/listExample.dir/build.make CMakeFiles/listExample.dir/examples/list.c.i
.PHONY : examples/list.c.i

examples/list.s: examples/list.c.s
.PHONY : examples/list.s

# target to generate assembly for a file
examples/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/listExample.dir/build.make CMakeFiles/listExample.dir/examples/list.c.s
.PHONY : examples/list.c.s

examples/map.o: examples/map.c.o
.PHONY : examples/map.o

# target to build an object file
examples/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapExample.dir/build.make CMakeFiles/mapExample.dir/examples/map.c.o
.PHONY : examples/map.c.o

examples/map.i: examples/map.c.i
.PHONY : examples/map.i

# target to preprocess a source file
examples/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapExample.dir/build.make CMakeFiles/mapExample.dir/examples/map.c.i
.PHONY : examples/map.c.i

examples/map.s: examples/map.c.s
.PHONY : examples/map.s

# target to generate assembly for a file
examples/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapExample.dir/build.make CMakeFiles/mapExample.dir/examples/map.c.s
.PHONY : examples/map.c.s

examples/queue.o: examples/queue.c.o
.PHONY : examples/queue.o

# target to build an object file
examples/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queueExample.dir/build.make CMakeFiles/queueExample.dir/examples/queue.c.o
.PHONY : examples/queue.c.o

examples/queue.i: examples/queue.c.i
.PHONY : examples/queue.i

# target to preprocess a source file
examples/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queueExample.dir/build.make CMakeFiles/queueExample.dir/examples/queue.c.i
.PHONY : examples/queue.c.i

examples/queue.s: examples/queue.c.s
.PHONY : examples/queue.s

# target to generate assembly for a file
examples/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/queueExample.dir/build.make CMakeFiles/queueExample.dir/examples/queue.c.s
.PHONY : examples/queue.c.s

examples/stack.o: examples/stack.c.o
.PHONY : examples/stack.o

# target to build an object file
examples/stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stackExample.dir/build.make CMakeFiles/stackExample.dir/examples/stack.c.o
.PHONY : examples/stack.c.o

examples/stack.i: examples/stack.c.i
.PHONY : examples/stack.i

# target to preprocess a source file
examples/stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stackExample.dir/build.make CMakeFiles/stackExample.dir/examples/stack.c.i
.PHONY : examples/stack.c.i

examples/stack.s: examples/stack.c.s
.PHONY : examples/stack.s

# target to generate assembly for a file
examples/stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stackExample.dir/build.make CMakeFiles/stackExample.dir/examples/stack.c.s
.PHONY : examples/stack.c.s

examples/vec.o: examples/vec.c.o
.PHONY : examples/vec.o

# target to build an object file
examples/vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vecExample.dir/build.make CMakeFiles/vecExample.dir/examples/vec.c.o
.PHONY : examples/vec.c.o

examples/vec.i: examples/vec.c.i
.PHONY : examples/vec.i

# target to preprocess a source file
examples/vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vecExample.dir/build.make CMakeFiles/vecExample.dir/examples/vec.c.i
.PHONY : examples/vec.c.i

examples/vec.s: examples/vec.c.s
.PHONY : examples/vec.s

# target to generate assembly for a file
examples/vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vecExample.dir/build.make CMakeFiles/vecExample.dir/examples/vec.c.s
.PHONY : examples/vec.c.s

src/comparators.o: src/comparators.c.o
.PHONY : src/comparators.o

# target to build an object file
src/comparators.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/comparators.c.o
.PHONY : src/comparators.c.o

src/comparators.i: src/comparators.c.i
.PHONY : src/comparators.i

# target to preprocess a source file
src/comparators.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/comparators.c.i
.PHONY : src/comparators.c.i

src/comparators.s: src/comparators.c.s
.PHONY : src/comparators.s

# target to generate assembly for a file
src/comparators.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/comparators.c.s
.PHONY : src/comparators.c.s

src/list.o: src/list.c.o
.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i
.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s
.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/list.c.s
.PHONY : src/list.c.s

src/map.o: src/map.c.o
.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/map.c.s
.PHONY : src/map.c.s

src/queue.o: src/queue.c.o
.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i
.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s
.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/stack.o: src/stack.c.o
.PHONY : src/stack.o

# target to build an object file
src/stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/stack.c.o
.PHONY : src/stack.c.o

src/stack.i: src/stack.c.i
.PHONY : src/stack.i

# target to preprocess a source file
src/stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/stack.c.i
.PHONY : src/stack.c.i

src/stack.s: src/stack.c.s
.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/stack.c.s
.PHONY : src/stack.c.s

src/vec.o: src/vec.c.o
.PHONY : src/vec.o

# target to build an object file
src/vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/vec.c.o
.PHONY : src/vec.c.o

src/vec.i: src/vec.c.i
.PHONY : src/vec.i

# target to preprocess a source file
src/vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/vec.c.i
.PHONY : src/vec.c.i

src/vec.s: src/vec.c.s
.PHONY : src/vec.s

# target to generate assembly for a file
src/vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctools.dir/build.make CMakeFiles/ctools.dir/src/vec.c.s
.PHONY : src/vec.c.s

test/test_list.o: test/test_list.c.o
.PHONY : test/test_list.o

# target to build an object file
test/test_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_list.c.o
.PHONY : test/test_list.c.o

test/test_list.i: test/test_list.c.i
.PHONY : test/test_list.i

# target to preprocess a source file
test/test_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_list.c.i
.PHONY : test/test_list.c.i

test/test_list.s: test/test_list.c.s
.PHONY : test/test_list.s

# target to generate assembly for a file
test/test_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_list.c.s
.PHONY : test/test_list.c.s

test/test_main.o: test/test_main.c.o
.PHONY : test/test_main.o

# target to build an object file
test/test_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_main.c.o
.PHONY : test/test_main.c.o

test/test_main.i: test/test_main.c.i
.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_main.c.i
.PHONY : test/test_main.c.i

test/test_main.s: test/test_main.c.s
.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_main.c.s
.PHONY : test/test_main.c.s

test/test_map.o: test/test_map.c.o
.PHONY : test/test_map.o

# target to build an object file
test/test_map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_map.c.o
.PHONY : test/test_map.c.o

test/test_map.i: test/test_map.c.i
.PHONY : test/test_map.i

# target to preprocess a source file
test/test_map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_map.c.i
.PHONY : test/test_map.c.i

test/test_map.s: test/test_map.c.s
.PHONY : test/test_map.s

# target to generate assembly for a file
test/test_map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_map.c.s
.PHONY : test/test_map.c.s

test/test_vec.o: test/test_vec.c.o
.PHONY : test/test_vec.o

# target to build an object file
test/test_vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_vec.c.o
.PHONY : test/test_vec.c.o

test/test_vec.i: test/test_vec.c.i
.PHONY : test/test_vec.i

# target to preprocess a source file
test/test_vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_vec.c.i
.PHONY : test/test_vec.c.i

test/test_vec.s: test/test_vec.c.s
.PHONY : test/test_vec.s

# target to generate assembly for a file
test/test_vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ctoolsTests.dir/build.make CMakeFiles/ctoolsTests.dir/test/test_vec.c.s
.PHONY : test/test_vec.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ctools"
	@echo "... ctoolsTests"
	@echo "... listExample"
	@echo "... mapExample"
	@echo "... queueExample"
	@echo "... stackExample"
	@echo "... vecExample"
	@echo "... examples/list.o"
	@echo "... examples/list.i"
	@echo "... examples/list.s"
	@echo "... examples/map.o"
	@echo "... examples/map.i"
	@echo "... examples/map.s"
	@echo "... examples/queue.o"
	@echo "... examples/queue.i"
	@echo "... examples/queue.s"
	@echo "... examples/stack.o"
	@echo "... examples/stack.i"
	@echo "... examples/stack.s"
	@echo "... examples/vec.o"
	@echo "... examples/vec.i"
	@echo "... examples/vec.s"
	@echo "... src/comparators.o"
	@echo "... src/comparators.i"
	@echo "... src/comparators.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
	@echo "... src/vec.o"
	@echo "... src/vec.i"
	@echo "... src/vec.s"
	@echo "... test/test_list.o"
	@echo "... test/test_list.i"
	@echo "... test/test_list.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
	@echo "... test/test_map.o"
	@echo "... test/test_map.i"
	@echo "... test/test_map.s"
	@echo "... test/test_vec.o"
	@echo "... test/test_vec.i"
	@echo "... test/test_vec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

